// This file is auto-generated by @hey-api/openapi-ts

export { createDomain, deleteDomain, getDomains, type Options, updateDomain } from './sdk.gen';
export type { ClientOptions, CreateDomainData, CreateDomainResponses, DeleteDomainData, DeleteDomainResponse, DeleteDomainResponses, Domain, DomainInsert, GetDomainsData, GetDomainsResponse, GetDomainsResponses, UpdateDomainData, UpdateDomainResponse, UpdateDomainResponses } from './types.gen';
