// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateDomainData, CreateDomainResponses, DeleteDomainData, DeleteDomainResponses, GetDomainsData, GetDomainsResponses, UpdateDomainData, UpdateDomainResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List domains
 */
export const getDomains = <ThrowOnError extends boolean = false>(options?: Options<GetDomainsData, ThrowOnError>): RequestResult<GetDomainsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetDomainsResponses, unknown, ThrowOnError>({ url: '/domains', ...options });

/**
 * Create a domain
 */
export const createDomain = <ThrowOnError extends boolean = false>(options: Options<CreateDomainData, ThrowOnError>): RequestResult<CreateDomainResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateDomainResponses, unknown, ThrowOnError>({
    url: '/domains',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a domain
 */
export const deleteDomain = <ThrowOnError extends boolean = false>(options: Options<DeleteDomainData, ThrowOnError>): RequestResult<DeleteDomainResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteDomainResponses, unknown, ThrowOnError>({ url: '/domains?id=eq.{id}', ...options });

/**
 * Update a domain
 */
export const updateDomain = <ThrowOnError extends boolean = false>(options: Options<UpdateDomainData, ThrowOnError>): RequestResult<UpdateDomainResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UpdateDomainResponses, unknown, ThrowOnError>({
    url: '/domains?id=eq.{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
