// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.yaml` | (string & {});
};

export type Domain = {
    id?: string;
    tenant_id?: string;
    domain?: string;
    created?: string;
};

export type DomainInsert = {
    domain: string;
};

export type GetDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/domains';
};

export type GetDomainsResponses = {
    /**
     * A list of domains
     */
    200: Array<Domain>;
};

export type GetDomainsResponse = GetDomainsResponses[keyof GetDomainsResponses];

export type CreateDomainData = {
    body: DomainInsert;
    path?: never;
    query?: never;
    url: '/domains';
};

export type CreateDomainResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteDomainData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/domains?id=eq.{id}';
};

export type DeleteDomainResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteDomainResponse = DeleteDomainResponses[keyof DeleteDomainResponses];

export type UpdateDomainData = {
    body: DomainInsert;
    path: {
        id: string;
    };
    query?: never;
    url: '/domains?id=eq.{id}';
};

export type UpdateDomainResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateDomainResponse = UpdateDomainResponses[keyof UpdateDomainResponses];
