services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.trustedIPs=10.0.0.0/16"
      - "--entrypoints.web.proxyProtocol=true"
      - "--entrypoints.web.proxyProtocol.trustedIPs=10.0.0.0/16"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  eye:
    build:
      context: ./eye
    depends_on:
      clickhouse:
        condition: service_healthy
      eye_flyway:
        condition: service_completed_successfully
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - POSTGRES_HOST=postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.http.routers.api.rule=Host(`api.analiza.dev`) || Host(`api.dev.analiza.lan`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=cors2"
      - "traefik.http.middlewares.cors2.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors2.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors2.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors2.headers.accesscontrolmaxage=200"
      - "traefik.http.middlewares.cors2.headers.addvaryheader=true"
  clickhouse:
    image: docker.io/bitnami/clickhouse:23.3.1
    #    user: "1001:1001" # Defined by the bitnami dockerfile https://github.com/bitnami/containers/blob/main/bitnami/clickhouse/23/debian-11/Dockerfile
    environment:
      - CLICKHOUSE_ADMIN_USER=eye_admin
      - CLICKHOUSE_ADMIN_PASSWORD=eye_super_duper_password
    volumes:
      - ./eye/clickhouse/init:/docker-entrypoint-initdb.d
      - type: bind
        source: ${ANALIZA_DATA_DIR:-/data/analiza}/clickhouse/data
        target: /bitnami/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "clickhouse client -u $${CLICKHOUSE_ADMIN_USER} --password $${CLICKHOUSE_ADMIN_PASSWORD} -q 'SELECT 1'",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "4"
          memory: 8G
  metabase:
    image: "metabase-clickhouse"
    build: metabase
    container_name: "metabase"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase_super_password
      - MB_DB_HOST=postgres
      - MB_REDIRECT_ALL_REQUESTS_TO_HTTPS=false
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.metabase.rule=Host(`metabase.analiza.dev`) || Host(`metabase.dev.analiza.lan`)"
      - "traefik.http.routers.metabase.entrypoints=web"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.1"
          memory: 500M
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgrest:
    image: postgrest/postgrest
    command:
      - "postgrest"
      - "/config/postgrest.conf"
    depends_on:
      postgrest_flyway:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: $ANALIZA_POSTGREST_CONFIG
        target: /config/postgrest.conf
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.admin.rule=Host(`admin.analiza.dev`) || Host(`admin.dev.analiza.lan`)"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.routers.admin.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://app.analiza.dev, http://app.dev.analiza.lan, http://localhost:5174"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=200"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
  postgrest_flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/eye_admin -user=postgres -password=super_secret_password -connectRetries=60 migrate
    volumes:
      - ./postgrest/schema:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: http://localhost:3001/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  eye_flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/eye_admin -defaultSchema=eye -user=postgres -password=super_secret_password -connectRetries=60 migrate
    volumes:
      - ./eye/postgres/schema:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  postgres:
    image: bitnami/postgresql:15.2.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DATABASE: postgres
      POSTGRESQL_EXTRA_FLAGS: "-c log_statement=all"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d/
      - type: bind
        source: ${ANALIZA_DATA_DIR:-/data/analiza}/postgres/data
        target: /bitnami/postgresql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
