version: '3'
services:
  eye:
    build:
      context: ./eye
    ports:
      - "8080:8080"
    depends_on:
      - eye_flyway
      - clickhouse
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - POSTGRES_HOST=postgres
  clickhouse:
    image: docker.io/bitnami/clickhouse:23
    environment:
      - CLICKHOUSE_ADMIN_USER=eye_admin
      - CLICKHOUSE_ADMIN_PASSWORD=eye_super_duper_password
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - ./eye/clickhouse/init:/docker-entrypoint-initdb.d

    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
  metabase:
    image: 'metabase-clickhouse'
    container_name: 'metabase_clickhouse'
    ports:
      - '3002:3000'
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase_super_password
      - MB_DB_HOST=postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 200M
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3001:3000"
    command:
      - "postgrest"
      - "/config/postgrest.conf"
    depends_on:
      - postgrest_flyway
    volumes:
      - ./postgrest:/config
  postgrest_flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/eye_admin -user=postgres -password=super_secret_password -connectRetries=60 migrate
    volumes:
      - ./postgrest/schema:/flyway/sql
    depends_on:
      - postgres
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      API_URL: http://localhost:3001/
  eye_flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/eye_admin -defaultSchema=eye -user=postgres -password=super_secret_password -connectRetries=60 migrate
    volumes:
      - ./eye/postgres/schema:/flyway/sql
    depends_on:
      - postgres
      - postgrest_flyway
  postgres:
    image: bitnami/postgresql:15.2.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DATABASE: postgres
    volumes:
      - "./postgres/init:/docker-entrypoint-initdb.d/"
      - "./postgres/data:/bitnami/postgres"

volumes:
  clickhouse_data:
    driver: local

