db-uri       = "postgres://postgrest:super_secret_password@postgres:5432/eye_admin"
db-schemas   = "api"
db-anon-role = "anon"

jwt-aud="local"
jwt-role-claim-key=".\"https://analiza.dev/role\""
jwt-secret = "super_secret_jwt_token_for_e2e_tests_which_must_be_32_chars"

server-port = 3000
openapi-server-proxy-uri = "http://localhost:3001"
openapi-mode = "ignore-privileges"
