version: '3'
services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:23
    environment:
      - CLICKHOUSE_ADMIN_USER=eye_admin
      - CLICKHOUSE_ADMIN_PASSWORD=eye_super_duper_password
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - ./init:/docker-entrypoint-initdb.d

    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  metabase:
    image: 'metabase-clickhouse'
    container_name: 'metabase_clickhouse'
    ports:
      - '3000:3000'
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

volumes:
  clickhouse_data:
    driver: local
