name: E2E Playwright Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ANALIZA_POSTGREST_CONFIG: postgrest/postgrest.test.conf
      COMPOSE_ARGS: -f docker-compose.yml -f docker-compose.ci.yml
    steps:
    - uses: actions/checkout@v4

    - name: Start services
      run: make start_detached

    - name: Update /etc/hosts
      run: |
        sudo echo "127.0.0.1 api.dev.analiza.lan" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 admin.dev.analiza.lan" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 metabase.dev.analiza.lan" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 openapi.dev.analiza.lan" | sudo tee -a /etc/hosts

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install eye-admin dependencies
      working-directory: ./eye-admin
      run: yarn

    - name: Install Playwright browsers
      working-directory: ./eye-admin
      run: npx playwright install --with-deps

    - name: Create .env file for E2E
      working-directory: ./eye-admin
      run: |
        cat << 'EOF' > .env
        VITE_METABASE_URL=http://metabase.dev.analiza.lan:8080
        VITE_POSTGREST_URL=http://admin.dev.analiza.lan:8080
        VITE_AUTH0_DOMAIN=eyelytics.eu.auth0.com
        VITE_AUTH0_CLIENT_ID=tCx2Ro9jepgtHYP3xDDCMqMyEOwwao0W
        VITE_AUTH0_AUDIENCE=local
        EOF

    - name: Run eye-admin UI
      working-directory: ./eye-admin
      env:
        VITE_E2E_MOCK_AUTH: 'true'
      run: yarn dev &

    - name: Run Playwright test
      working-directory: ./eye-admin
      run: npx playwright test e2e.spec.ts

    - name: Read tenant ID
      id: tenant
      run: echo "::set-output name=id::123e4567-e89b-12d3-a456-426614174000"

    - name: Send test event
      run: |
        curl -X POST -H "Content-Type: application/json" -H "Host: test.analiza.lan" -d '{"t":"view","p":"/","u":"${{ steps.tenant.outputs.id }}","r":"https://example.com"}' http://localhost/eye

    - name: Verify event in ClickHouse
      run: |
        sleep 5 # Wait for the event to be processed
        RESULT=$(docker compose $COMPOSE_ARGS exec -T clickhouse clickhouse-client -u eye_admin --password eye_super_duper_password -q "SELECT count() FROM eye.events WHERE tenant_id = '${{ steps.tenant.outputs.id }}'")
        if [ "$RESULT" -ne 1 ]; then
          echo "Event not found in ClickHouse"
          docker compose $COMPOSE_ARGS logs eye
          exit 1
        fi
        echo "Event found in ClickHouse"

    - name: Stop services
      if: always()
      run: make stop

    - name: Show Docker logs on failure
      if: failure()
      run: docker compose $COMPOSE_ARGS logs
